# Generated by Django 6.0.6 on 2026-10-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(default='exit'),
            preserve_default=False,
        ),
    ]
