# Generated by Django 6.0.6 on 2026-10-03 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_inquiry_testimony'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiry',
            options={'verbose_name_plural': 'Inquiries'},
        ),
        migrations.AlterModelOptions(
            name='personalinformation',
            options={'verbose_name_plural': 'Personal Information'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='testimony',
            options={'verbose_name_plural': 'Testimonies'},
        ),
    ]
